### ISSUE TITLE
IntlMessageFormat and custom formatters

### ISSUE THREAD

**Issue by kachkaev** [i18next/i18next-icu#5] opened 2018-09-01 22:23 UTC
Hi @jamuhl 👋 

I'm opening this issue to discuss how custom formatters could be added to `i18next-icu`. It seems that `MessageFormat` you are leveraging has this functionality already, it's jut not exposed into the API of `i18next-icu`. See the docs here:

https://messageformat.github.io/messageformat/page-guide#toc11__anchor
https://messageformat.github.io/messageformat/MessageFormat.html#addFormatters

The reason why I have started exploring custom formatters is because I would like to output values with certain numbers of fractional digits, e.g. 1, 3 or 6.

Here's how my translation files could look in an ideal world:

```json
{
  "example1": "Our value is equal to {value, numberWithThreeFractionalDigits}.",
  "example2": "Our value is roughly equal to {value, numberWithFD, 1}, but if you like things to be precise, it is {value, numberWithFD, 6}.",
}
```

I'm not yet sure what I'd write in `addFormatters()` to define `numberWithThreeFractionalDigits`, `numberWithFD` or whatever. But before I get there, it'd be great to know how `addFormatters()` could be called from `i18next-icu`. I see you are doing something smart about memorisation of `IntlMessageFormat` here, which needs to be taken into account:

https://github.com/i18next/i18next-icu/blob/133d2976d8ab22bcd6c3afd8da914f32f7e32084/src/index.js#L24

https://github.com/i18next/i18next-icu/blob/133d2976d8ab22bcd6c3afd8da914f32f7e32084/src/index.js#L45-L53

Being able to define custom formatters in the ICU plugin will make it as extensible as the [main formatter](https://www.i18next.com/translation-function/formatting). And in turn this will add even  more value to the synergy i18next ecosystem creates!

**Comment by jamuhl** [comment] 2018-09-02 07:42
hm...not sure if people add customFormatters per message or just add them like once as default to all messages...

in i18next we have the https://www.i18next.com/translation-function/formatting

we might just have some additional option added to icu init like:


```js
i18next
  .use(ICU)
  .init({
    i18nFormat: {
      localeData: fr, // you also can pass in array of localeData

formatters: {
  upcase: function(v) { return v.toUpperCase(); },
  locale: function(v, lc) { return lc; },
  prop: function(v, lc, p) { return v[p] }
}

    }
  });
```
those get added to all compiled message functions here: https://github.com/i18next/i18next-icu/blob/master/src/index.js#L50

Sorry just take a quick look...not sure if i got it right how it should behave.

**Comment by kachkaev** [comment] 2018-09-02 18:45
According to [the docs](https://github.com/yahoo/intl-messageformat#intlmessageformat-constructor), `IntlMessageFormat` expects a map of formatters to be the third parameter. It is not passed to the constructor at the moment:

https://github.com/i18next/i18next-icu/blob/133d2976d8ab22bcd6c3afd8da914f32f7e32084/src/index.js#L50

**Comment by kachkaev** [comment] 2018-09-02 18:48
From the user point of view the solution could look something like:

```js
const icu = new ICU();
icu.addLocaleData(fr);
icu.addFormatters({
  upcase: function(v) { return v.toUpperCase(); },
  locale: function(v, lc) { return lc; },
  prop: function(v, lc, p) { return v[p] }
});
i18n.use(icu);
```

**Comment by jamuhl** [comment] 2018-09-02 19:03
we could provide both...an additional addFormatters function and passing them via options: https://github.com/i18next/i18next-icu/blob/133d2976d8ab22bcd6c3afd8da914f32f7e32084/src/index.js#L21

**Comment by kachkaev** [comment] 2018-09-02 19:07
Yeah that'd be cool. I'll be happy to test this feature if you are fancy an experiment 😉

**Comment by jamuhl** [comment] 2018-09-03 10:53
Will see when i find time...not hard to add this...more a problem of my time management 😭

**Comment by kachkaev** [comment] 2018-09-03 10:56
No worries, I know your pain! Just ping me when you want to go for it and I'll find some time to give the feature a test 😉

**Comment by jamuhl** [comment] 2018-09-03 15:48
hm...just started with it...as i thought simplest of all the shit i got planned....oh no...not really:

https://github.com/yahoo/intl-messageformat/issues/121#issuecomment-176043615

IntlMessageFormat custom formatters are no custom formatters just some...idk what they are: https://github.com/yahoo/intl-messageformat#user-defined-formats

And currently i do not expect them to do anything in this direction. So only option i currently see would be moving to messageformat

**Comment by kachkaev** [comment] 2018-09-03 16:48
😅 oh gosh that's confusing indeed! Looks like my brain mixed-up [`MessageFormat` formatters](https://messageformat.github.io/messageformat/page-guide#toc11__anchor) with [`IntlMessageFormat` user-defined formats](https://github.com/yahoo/intl-messageformat#user-defined-formats) – I thought they were the same thing!

Although user-defined formats `IntlMessageFormat` are not functions as I originally expected, injecting them from `i18next` may still make sense. Check out the options they pass in their [example](https://github.com/yahoo/intl-messageformat#user-defined-formats) you referred to:

```js
var msg = new IntlMessageFormat('The price is: {price, number, USD}', 'en-US', {
    number: {
        USD: {
            style   : 'currency',
            currency: 'USD'
        }
    }
});
```

This `{ style: 'currency', currency: 'USD' }` looks very much like what gets passed to the [browser's `NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) or its polyfill. This means that we can do something like:

```js
const icu = new ICU();
icu.addLocaleData(fr);
icu.addUserDefinedFormats({
  number: {
    THREE_FRACTIONAL_DIGITS: {
      minimumSignificantDigits: 3,
      maximumSignificantDigits: 3
    },
    ROUGH: {
      maximumSignificantDigits: 1
    },
    VERY_PRECISE: {
      minimumSignificantDigits: 6,
    },
  }
});
i18n.use(icu);
```

And then: 
```json
{
  "example1": "Our value is equal to {value, number, THREE_FRACTIONAL_DIGITS}.",
  "example2": "Our value is roughly equal to {value, number, ROUGH}, but if you like things to be precise, it is {value, number, VERY_PRECISE}.",
}
```

There are [plenty of options](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat#Parameters) `NumberFormat` accepts, which makes it pretty powerful. Turns out we can solve lots of formatting issues just keeping things declarative – no need to use functions!

WDYT?

**Comment by jamuhl** [comment] 2018-09-03 20:05
hope tests are sufficient to get how it works: https://github.com/i18next/i18next-icu/commit/9607f391633f739bddc8b2b2bfc3f1d0c48850a2

currently running travis...will npm publish if all green

**Comment by jamuhl** [comment] 2018-09-03 20:08
i18next-icu@0.5.0

**Comment by kachkaev** [comment] 2018-09-03 20:09
Outstanding 🎉 I'll test your commit soon! Just one quick note before you've released this: should the method be called `addFormatters` or `addUserDefinedFormats` as I suggest in the more recent comment? The second name slightly better reflects the origin of the feature, but I don't have a strong opinion here.

**Comment by kachkaev** [comment] 2018-09-03 20:10
Ouch, looks like I was a bit late 😅

**Comment by kachkaev** [comment] 2018-09-03 20:16
Just noticed that the third argument in `IntlMessageFormat` constructor is called formats, not formatters: https://github.com/yahoo/intl-messageformat/blob/master/index.d.ts#L2

It does not influence the behaviour in anyway, just makes things a bit less obscure (especially given the fact that the things are confusing already 😅 ).

Let me give your new version a try first anyway! Given that it's unlikely that too many people will be use custom formats from day one, I'll be happy to see the methods renamed if you agree with me that this can positively influence the coherence of `18next-icu`.

**Comment by kachkaev** [comment] 2018-09-03 21:27
Custom formats work well when passed to the ICU constructor:

```js
const icu = new ICU({
  formatters: {
    number: {
      THREE_FRACTION_DIGITS: {
        minimumFractionDigits: 3,
        maximumFractionDigits: 3,
      },
    },
  },
});
```

This is truly great! 🎉 

However, when I try using `addFormatters`, the numbers format as if my custom format did not exist:

```js
const icu = new ICU();
icu.addFormatters({
  number: {
    PRICE: {
      minimumFractionDigits: 3,
    },
  },
});
```

I could get as far as adding several `console.log()` calls to `node_modules/i18next-icu/dist/commonjs/index.js` and noticed something strange. When `formatters` are passed as options, `this.formatters` are defined in `parse()`. When calling `addFormatters()`, `this.formatters` are also defined in this method, but are undefined in the following `parse()` calls. Does it give any hints?

---
One thing worth noting in my most recent example is that I replaced `minimumSignificantDigits: 3` with `minimumFractionDigits: 3` — significant digits are both fractional and integer ones combined. I also renamed `THREE_FRACTIONAL_DIGITS` with `THREE_FRACTION_DIGITS` for consistency with MessageFormat.

**Comment by jamuhl** [comment] 2018-09-04 06:55
changed test to use the add function -> works on my machine and travis...

could you take another look - as i can't reproduce that. Only thing i know is having formats on init and additional adding via add function will overwrite them.

also done renamings...hope you like that

**Comment by jamuhl** [comment] 2018-09-04 06:57
i18next-icu@0.6.0 includes changes.

**Comment by kachkaev** [comment] 2018-09-04 07:05
Great, thank you 🎉  👏  I'll try the changes tonight.

**Comment by kachkaev** [comment] 2018-09-04 23:28
Hi @jamuhl, just a quick heads up. I ran out of time this evening, so have to postpone my tests for another day. Hope this can be tomorrow – I'll let you know once I get there. Sorry for this.

**Comment by jamuhl** [comment] 2018-09-05 05:49
@kachkaev no problem...if there is something breaking it will be no big deal...i think after this i will change version to v1.0.0 anyway.

**Comment by dyniper** [comment] 2018-12-15 00:13
I did some testing with this. The formatters passed in the ctor options works, but calling addUserDefinedFormats doesn't actually add the formats.

**Comment by kachkaev** [comment] 2018-12-15 08:37
@dyniper this worked for me to register a custom ICU format:

```js
import * as ICU from "i18next-icu";
const icu = new ICU({
  formats: {
    number: {
      PRICE: {
        minimumFractionDigits: 2,
        useGrouping: false,
      },
    },
  },
});
```

**Comment by dyniper** [comment] 2018-12-17 19:55
Yes, this work, but if you do:
```
import * as ICU from "i18next-icu";
const icu = new ICU();
icu.addUserDefinedFormats({
  formats: {
    number: {
      PRICE: {
        minimumFractionDigits: 2,
        useGrouping: false,
      },
    },
  },
});
```
, that one doesn't work. I don't mind having to provide the formats in the ctor, but if there is a method to add them after constructing the object, it should work, otherwise, remove the method.

**Comment by jamuhl** [comment] 2018-12-18 07:30
@dyniper PR with a fix or removing that is welcome

**Comment by jamuhl** [comment] 2018-12-20 06:47
@dyniper sounds like a good plan 👍

**Closed** 2018-12-20 06:47 UTC

**Comment by developerdanwu** [comment] 2023-07-21 03:15
First of all, thanks for creating such a fantastic tool and my apologies for commenting on such an old issue. However, I was trying to use the custom formatter like the code below and one of my translators appears to want a 24 hour time whereas for the rest of the locales I want 12 hour time. Is it possible to set these custom formatters based on the locale? Eg. if user is on en it would one set of configs and another locale another set. If this is not an existing feature, I am willing to contribute and open a PR for this if given some direction on what would be the best solution. Thanks!

```ts
const icu = new ICU({
  parseLngForICU: (lng) => {
    return lng === 'en' ? 'en-GB' : lng;
  },
  memoize: true,
  formats: {
    number: {},
    date: {
      long: {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
        weekday: 'long',
      },
      full: {
        hour12: true,
        day: 'numeric',
        month: 'short',
        year: 'numeric',
        weekday: 'long',
        hour: '2-digit',
        minute: '2-digit',
      },
    },
    time: {
      short: {
        hour12: true,
      },
    },
  },
});

```
